const TrendingData = [
    {
      id: 1,
      is_available: true,
      is_featured: true,
      image: 'https://example.com/image1.png',
      title: 'Product 1',
      price: 20,
      discount_price: 15,
      quantity: 10,
    },
    {
      id: 2,
      is_available: true,
      is_featured: false,
      image: 'https://example.com/image2.png',
      title: 'Product 2',
      price: 25,
      discount_price: 20,
      quantity: 5,
    },
    {
      id: 3,
      is_available: true,
      is_featured: true,
      image: 'https://example.com/image3.png',
      title: 'Product 3',
      price: 30,
      discount_price: 25,
      quantity: 0,
    },
    {
        id: 1,
        is_available: true,
        is_featured: true,
        image: 'https://example.com/image1.png',
        title: 'Product 1',
        price: 20,
        discount_price: 15,
        quantity: 10,
      },
      {
        id: 2,
        is_available: true,
        is_featured: false,
        image: 'https://example.com/image2.png',
        title: 'Product 2',
        price: 25,
        discount_price: 20,
        quantity: 5,
      },
      {
        id: 3,
        is_available: true,
        is_featured: true,
        image: 'https://example.com/image3.png',
        title: 'Product 3',
        price: 30,
        discount_price: 25,
        quantity: 0,
      },
      {
        id: 1,
        is_available: true,
        is_featured: true,
        image: 'https://example.com/image1.png',
        title: 'Product 1',
        price: 20,
        discount_price: 15,
        quantity: 10,
      },
      {
        id: 2,
        is_available: true,
        is_featured: false,
        image: 'https://example.com/image2.png',
        title: 'Product 2',
        price: 25,
        discount_price: 20,
        quantity: 5,
      },
      {
        id: 3,
        is_available: true,
        is_featured: true,
        image: 'https://example.com/image3.png',
        title: 'Product 3',
        price: 30,
        discount_price: 25,
        quantity: 0,
      },
  ];
  
  export default TrendingData;
  